/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: 6cb95bdbcb46fd8be67870b5895dd064)
interface __BaseEnv_Env {
	CREATION_LIMIT: RateLimit;
	CREATION_GLOBAL: RateLimit;
	REQUEST_LIMIT: RateLimit;
	ALLOWED_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173" | "https://timzegveld.github.io";
	SESSIONS: DurableObjectNamespace<import("./index").LiveSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "LiveSession";
	}
	interface DevelopmentEnv {
		CREATION_LIMIT: RateLimit;
		CREATION_GLOBAL: RateLimit;
		REQUEST_LIMIT: RateLimit;
		ALLOWED_ORIGINS: "http://127.0.0.1:5173,http://localhost:5173";
		SESSIONS: DurableObjectNamespace<import("./index").LiveSession>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
